[package]
name = "sqlite-browser"
version = "0.1.0"
edition = "2024"

[dependencies]
gpui = { git = "https://github.com/zed-industries/zed" }
anyhow = "1.0"
thiserror = "1.0"
byteorder = "1.5"
notify = "6.0"
